<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
xmlns:xacro="http://ros.org/wiki/xacro"
>
  <xacro:macro name="lidar_sensor" params="name parent *origin ros_topic update_rate min_range max_range field_of_view_h field_of_view_v ray_count_h ray_count_v">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.000000017" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.000000017" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.2" />
          <!--<mesh filename="package://cvg_sim_gazebo/meshes/sonar_sensor/max_sonar_ez4.dae"/>-->
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.2" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${name}_link">
      <sensor type="ray" name="${name}">
        <update_rate>${update_rate}</update_rate>
        <visualize>true</visualize>
        <ray>
          <range>
            <min>${min_range}</min>
            <max>${max_range}</max>
            <resolution>0.01</resolution>
          </range>
          <scan>
            <horizontal>
              <samples>${ray_count_h}</samples>
              <min_angle>-${field_of_view_h/2}</min_angle>
              <max_angle>${field_of_view_h/2}</max_angle>
            </horizontal>
            <vertical>
              <samples>${ray_count_v}</samples>
              <min_angle>-${field_of_view_v/2}</min_angle>
              <max_angle>${field_of_view_v/2}</max_angle>
            </vertical>
          </scan>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>

        <plugin name="gazebo_ros_${name}_controller" filename="libhector_gazebo_ros_lidar.so">
          <gaussianNoise>0.000</gaussianNoise>
          <offset>0.0 </offset>
          <drift>0.0</drift>
	  <driftFrequency>0.0</driftFrequency>
          <topicName>${ros_topic}</topicName>
          <frameId>${name}_link</frameId>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
